baseURL = "https://penne.blog"
languageCode = "en-us"
title = "Penelopes Blog"
theme = "hugo-texify3"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 2
[taxonomies]
tags = "tags"
[params]
title="Penne Not Pasta's Blog"
description = "my silly little blog :3"
images = ['static/images/favicon.ico']
footnote = """
Follow me on <a class=link href=https://github.com/penne-not-pasta target=_blank rel=noopener>GitHub</a>,
<a class=link href=/index.xml>RSS</a>
"""
keywords = ["hugo", "blog", "crochet", "crocheting", "art", "arts", "crafts", "crafting", "tech", "programming", "software", "development", "web", "design"]
customCSS = []
customJS = []
[params.commentengine]
code = """
<script src="https://giscus.app/client.js"
        data-repo="penne-not-pasta/blog"
        data-repo-id="R_kgDOQBvWOg"
        data-category="General"
        data-category-id="DIC_kwDOQBvWOs4Cxi_-"
        data-mapping="pathname"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
"""
dateFormat = "January 2, 2006"
emphasisWithDots = true
since = "2025"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "120%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false
[params.buymeacoffee]
code = ""
[params.sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true