baseURL = "https://penne.blog"
languageCode = "en-us"
title = "Penelopes Blog"
theme = "hugo-texify3"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 2
[taxonomies]
tags = "tags"
[params]
title="Penne Not Pasta's Blog"
description = "my silly little blog :3"
images = ['static/images/favicon.ico']
footnote = """
Follow me on <a class=link href=https://github.com/penne-not-pasta target=_blank rel=noopener>GitHub</a>,
<a class=link href=/index.xml>RSS</a>
"""
keywords = ["hugo", "blog", "crochet", "crocheting", "art", "arts", "crafts", "crafting", "tech", "programming", "software", "development", "web", "design"]
customCSS = []
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = true
since = "2025"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "120%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false
[params.sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = false
reddit = true
whatsapp = true
hackernews = false
telegram = true